name: afrisenti
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pyarrow
  - pip:
      - datasets
      - transformers
      - accelerate
      - evaluate
      - torch
      - emoji
      - tqdm
